#!/usr/bin/env bash
# Configures an Ubuntu server with the following requirements:
# - localhost resolves to 127.0.0.2
# - facebook.com resolves to 8.8.8.8

cp /etc/hosts ~/hosts.new

sed -i 's/127\.0\.0\.1\s\+localhost/127.0.0.2 localhost/g' ~/hosts.new

grep -q "facebook.com" ~/hosts.new && sed -i 's/.*facebook\.com/8.8.8.8 facebook.com/g' ~/hosts.new || echo "8.8.8.8 facebook.com" >> ~/hosts.new

cp -f ~/hosts.new /etc/hosts

rm ~/hosts.new
