#!/usr/bin/env bash

# Configures localhost to 127.0.0.2
# and facebook.com to 8.8.8.8 in /etc/hosts

sudo sed -i 's/^\(127\.0\.0\.1\s\+\)localhost/\1127.0.0.2 localhost/' /etc/hosts

sudo sed -i '/facebook\.com/d' /etc/hosts

echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null
