#!/usr/bin/env bash
# Displays all active IPv4 IPs on the machine it's executed on

if command -v ip >/dev/null 2>&1; then
    ip -4 addr show | grep -oP '(?<=inet\s)\d+(\.\d+){3}'
elif command -v ifconfig >/dev/null 2>&1; then
    ifconfig | grep -oP '(?<=inet\s)\d+(\.\d+){3}'
else
    hostname -I | tr ' ' '\n' | grep -E '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$'
fi